version: '3.9'

services:
  webshop-db:
    container_name: webshop-db
    image: ${DB_IMAGE}
    ports:
      - ${DB_PORT_ON_HOST}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart:
      unless-stopped
    networks:
      - webshop_net

networks:
  webshop_net:
